// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Magazyn.Models
{
    public partial class Appointments
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public DateTime? Start { get; set; }
        public DateTime? End { get; set; }
        public int? ResourceId { get; set; }
        public int? IdUser { get; set; }
        public ulong? AllDay { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public int? Status { get; set; }
        public int? Label { get; set; }
        public string ResourceIds { get; set; }
        public string ReminderInfo { get; set; }
        public string CustomField1 { get; set; }
    }
}