// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Magazyn.Models
{
    public partial class Resources
    {
        public int Id { get; set; }
        public string Description { get; set; }
    }
}