// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Magazyn.Models
{
    public partial class Taskdependencies
    {
        public int Id { get; set; }
        public int? ParentId { get; set; }
        public int? DependentId { get; set; }
        public int Type { get; set; }
    }
}