// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Magazyn.Models
{
    public partial class Tbgrupa
    {
        

        [Key]
        public int idgrupa { get; set; }
        public string NazwaGrupa { get; set; }
        public string SymbolGrupa { get; set; }

      //  public virtual ICollection<Tbtowar> Tbtowar { get; set; }
        public virtual Tbtowar Tbtowar { get; set; }
    }
}