// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Magazyn.Models
{
    public  class Tbjm
    {
        
        [Key]
        public int Idjm { get; set; }
        public string Jm { get; set; }
        public string Opis { get; set; }

   //     public virtual ICollection<Tbtowar> Tbtowar { get; set; }
        public virtual Tbtowar Tbtowar { get; set; }
    }
}