// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Magazyn.Models
{
    public partial class Tbmaszyna
    {
        public Tbmaszyna()
        {
            Tbpodzespol = new HashSet<Tbpodzespol>();
            TbpozycjeRozchod = new HashSet<TbpozycjeRozchod>();
        }


        [Key]
        public int Idmaszyna { get; set; }
        public string NazwaMaszyna { get; set; }
        public string OpisMaszyna { get; set; }
        public string EanMaszyna { get; set; }
        public string NumerMaszyna { get; set; }
        public string UwagiMaszyna { get; set; }

        public virtual ICollection<Tbpodzespol> Tbpodzespol { get; set; }
        public virtual ICollection<TbpozycjeRozchod> TbpozycjeRozchod { get; set; }
    }
}