// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Magazyn.Models
{
    public partial class Tbpozycje
    {
        public Tbpozycje()
        {
            Tbprzyjecie = new HashSet<Tbprzyjecie>();
        }

        [Key]
        public int Idpozycje { get; set; }
        public int Ftowar { get; set; }
        public float? Ilosc { get; set; }
        public decimal? Cena { get; set; }
        public string Uwagi { get; set; }

        public virtual Tbtowar FtowarNavigation { get; set; }
        public virtual ICollection<Tbprzyjecie> Tbprzyjecie { get; set; }
    }
}