// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Magazyn.Models
{
    public partial class TbpozycjeRozchod
    {
        [Key]
        public int IdpozycjeRozchod { get; set; }
        public int? Idrozchod { get; set; }
        public int? Ftowar { get; set; }
        public int? Fmaszyna { get; set; }
        public int? Fpodzespol { get; set; }
        public decimal? Ilosc { get; set; }
        public int? Fpobierajacy { get; set; }
        public decimal StanMagazynu { get; set; }

        public virtual Tbmaszyna FmaszynaNavigation { get; set; }
        public virtual Tbuser FpobierajacyNavigation { get; set; }
        public virtual Tbpodzespol FpodzespolNavigation { get; set; }
        public virtual Tbtowar FtowarNavigation { get; set; }
        public virtual Tbrozchod IdrozchodNavigation { get; set; }
    }
}