// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Magazyn.Models
{
    public partial class Tbpodzespol
    {
        public Tbpodzespol()
        {
            TbpozycjeRozchod = new HashSet<TbpozycjeRozchod>();
        }

        [Key]
        public int Idpodzespol { get; set; }
        public int? Maszyna { get; set; }
        public string Nazwa { get; set; }
        public string Opis { get; set; }
        public string EanPodzespol { get; set; }

        public virtual Tbmaszyna MaszynaNavigation { get; set; }
        public virtual ICollection<TbpozycjeRozchod> TbpozycjeRozchod { get; set; }
    }
}