// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Magazyn.Models
{
    public partial class Tbprzyjecie
    {
        [Key]
        public int Idprzyjecie { get; set; }
        public string Numer { get; set; }
        public DateTime? Data { get; set; }
        public int Fpozycje { get; set; }
        public string Uwagi { get; set; }
        public int Fdokument { get; set; }

        public virtual Tbdokument FdokumentNavigation { get; set; }
        public virtual Tbpozycje FpozycjeNavigation { get; set; }
    }
}