// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Magazyn.Models
{
    public partial class Tbrozchod
    {
        public Tbrozchod()
        {
            TbpozycjeRozchod = new HashSet<TbpozycjeRozchod>();
        }
        [Key]
        public int Idrozchod { get; set; }
        public int? Nr { get; set; }
        public int? Miesiac { get; set; }
        public int? Rok { get; set; }
        public int? Fdokument { get; set; }
        public DateTime? Data { get; set; }
        public string Numer { get; set; }
        public string Uwagi { get; set; }
        public DateTime? Stamp { get; set; }

        public virtual Tbdokument FdokumentNavigation { get; set; }
        public virtual ICollection<TbpozycjeRozchod> TbpozycjeRozchod { get; set; }
    }
}