// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Magazyn.Models
{
    public partial class Tbsrodki
    {
        [Key]
        public int IdSrodki { get; set; }
        public string Numer { get; set; }
        public string Nazwa { get; set; }
        public string Opis { get; set; }
        public string CentrumKosztow { get; set; }
        public string Ot { get; set; }
        public string DokumentDodatkowy { get; set; }
        public string NrSeryjny { get; set; }
        public string RokProdukcji { get; set; }
        public string MiejsceSkladowania { get; set; }
        public string Odpowiedzialny { get; set; }
        public string DokumentZakupu { get; set; }
        public DateTime? DataZakupu { get; set; }
        public DateTime? DataLikwidacji { get; set; }
        public string DokumentLikwidacji { get; set; }
        public int? Status { get; set; }
        public int? Aktywny { get; set; }
        public int? Zlikwidowany { get; set; }
    }
}