// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Magazyn.Models
{
    public partial class Tbtowar
    {
        public Tbtowar()
        {
            Tbpozycje = new HashSet<Tbpozycje>();
            TbpozycjeRozchod = new HashSet<TbpozycjeRozchod>();
        
            
        }

        [Key]
        public int Idtowar { get; set; }
        public string Nazwa { get; set; }
        public string Indeks { get; set; }
        public string Ean { get; set; }
        public int? Fjm { get; set; }
        public int? Pozycja { get; set; }
        public int? Fgrupa { get; set; }
        public string Opis { get; set; }
        public int? Ilosciowa { get; set; }

  
        public virtual ICollection<Tbpozycje> Tbpozycje { get; set; }
        public virtual ICollection<TbpozycjeRozchod> TbpozycjeRozchod { get; set; }
        public virtual ICollection<Tbgrupa> Tbgrupas { get; set; }
        public virtual ICollection<Tbjm> Tbjms { get; set; }


    }
}