// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Magazyn.Models
{
    public partial class Tbuser
    {
        public Tbuser()
        {
            TbpozycjeRozchod = new HashSet<TbpozycjeRozchod>();
        }
        [Key]
        public int Iduser { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public int? Administrator { get; set; }
        public string User { get; set; }
        public string Ean_User { get; set; }
        public string Password { get; set; }
        public int? Logowanie { get; set; }
        public int? Aktywny { get; set; }

        public virtual ICollection<TbpozycjeRozchod> TbpozycjeRozchod { get; set; }
    }
}