// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using MySQL.Data;

namespace Magazyn.Models
{
    public partial class MczeContext : DbContext
    {
        public MczeContext()
        {
        }

        public MczeContext(DbContextOptions<MczeContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Appointments> Appointments { get; set; }
        public virtual DbSet<Resources> Resources { get; set; }
        public virtual DbSet<Taskdependencies> Taskdependencies { get; set; }
        public virtual DbSet<Tbdokument> Tbdokument { get; set; }
        public virtual DbSet<Tbgrupa> Tbgrupa { get; set; }
        public virtual DbSet<Tbjm> Tbjm { get; set; }

        public virtual DbSet<Tbmaszyna> Tbmaszyna { get; set; }
        public virtual DbSet<Tbpodzespol> Tbpodzespol { get; set; }
        public virtual DbSet<Tbpozycje> Tbpozycje { get; set; }
        public virtual DbSet<TbpozycjeRozchod> TbpozycjeRozchod { get; set; }
        public virtual DbSet<Tbprzyjecie> Tbprzyjecie { get; set; }
        public virtual DbSet<Tbrozchod> Tbrozchod { get; set; }
        public virtual DbSet<Tbsrodki> Tbsrodki { get; set; }
        public virtual DbSet<Tbtowar> Tbtowar { get; set; }
        public virtual DbSet<Tbuser> Tbuser { get; set; }
         
        
    }
}